# Sample workflow for building and deploying a Hugo site with the Doks theme to GitHub Pages
name: Deploy Hugo site with Doks theme to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Git
        run: sudo apt-get install git -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Doks theme
        run: git clone --depth 1 https://github.com/h-enk/doks.git themes/doks
      - name: Create Hugo Site
        run: hugo new site myhugosite
      - name: Copy Config
        run: cp -r ./themes/doks/exampleSite/* ./myhugosite/
      - name: Install Node.js dependencies
        run: "[[ -f myhugosite/package-lock.json || -f myhugosite/npm-shrinkwrap.json ]] && npm ci --prefix myhugosite || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.repository.name }}/gh-pages/"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./myhugosite/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: myhugosite/public
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: myhugosite/public
